package com.sbi.oem.enums;

public enum RecommendationStatusEnum {

	CREATED, APPROVED_BY_APPOWNER, APPROVED_BY_AGM, REJECTED_BY_AGM, REJECTED_BY_APPOWNER, REVERTED_BY_AGM,
	RECOMMENDATION_APPROVED, RECCOMENDATION_REJECTED, UPDATE_DEPLOYMENT_DETAILS, RECOMMENDATION_STATUS_CHANGED, RECOMMENDATION_RELEASED
}
